name: Publish
on:
  push:
    branches:
      - main
      - beta
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore
      - .yarnrc
      - LICENSE
  pull_request:
    paths-ignore:
      - '**.md'
      - .editorconfig
      - .gitignore
      - .yarnrc
      - LICENSE

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Retrieve additional tag data
        run: git fetch --tags --force

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: yarn install

      - name: Generate types
        run: yarn generate-types

      - name: Get Next Version
        run: yarn semantic-release
        id: get-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        if: steps.get-next-version.outputs.new-release-published == 'true'
        run: yarn npm publish --tag ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
